name: Auto Linter
on: 
  push:
    paths: "*.py"

jobs: 
   code: 
     runs-on: ubuntu-latest
   
     steps: 
       - name: checkout the code
         uses: actions/checkout@v4
       - name: install linter
         run: pip install ruff
       - name: run linter
         run: ruff check .
         name: setup python
         uses: actions/setup-python@v5
         with:
            python-version: "3.14"
        
       

  
